version: "3"
services:
    web-1:
        build: ./web-1
        ports:
            - "5020:80"
        environment:
            - Web2Url=http://web-2
        depends_on:
            - web-2
            
    web-2:
        build: ./web-2
        ports:
            - "5021:80"